# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0006_auto_20161129_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataproduct',
            name='dmp_URL',
        ),
        migrations.AddField(
            model_name='project',
            name='ODMP_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dmp_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='moles_URL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dmp.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[(b'Proposal', b'Proposal'), (b'NotFunded', b'Not Funded'), (b'NotStarted', b'Not Started'), (b'Active', b'Active'), (b'NoData', b'No Data'), (b'EndedWithDataToCome', b'Ended with data to come'), (b'Defaulted', b'Defaulted'), (b'NoDataForUs', b'No data for us'), (b'Complete', b'Complete')], max_length=200, null=True),
        ),
    ]
