# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0013_grant_pi_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='pi_email',
            new_name='data_email',
        ),
    ]
