# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0018_auto_20170120_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('reminder', models.CharField(choices=[(b'1 week', b'1 Week'), (b'2 weeks', b'2 Weeks'), (b'1 month', b'1 Month'), (b'3 months', b'3 Months'), (b'-6 months', b'6 Months before end date'), (b'-3 months', b'3 Months before end date'), (b'-1 month', b'1 Month before end date')], max_length=200, verbose_name=b'Reminder Interval')),
                ('due_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmp.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_ref',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Short Name'),
        ),
    ]
