# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmp', '0018_auto_20170106_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=20)),
                ('scope', models.CharField(max_length=250)),
                ('access_token', models.CharField(max_length=50)),
                ('refresh_token', models.CharField(max_length=50)),
                ('expires_at', models.FloatField()),
                ('expires_in', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Token',
            },
        ),
        migrations.AlterField(
            model_name='draftdmp',
            name='draft_dmp_name',
            field=models.CharField(default=b'Draft DMP', max_length=200),
        ),
    ]
