# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0022_reminder_state'),
        ('dmp', '0024_auto_20170113_1626'),
    ]

    operations = [
    ]
