# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0030_auto_20180205_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='programme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
