# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0032_project_scisupcontact2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='preservation_plan',
            field=models.CharField(blank=True, choices=[(b'Reference', b'Reference data with principal use to provide evidence for publication'), (b'Structured', b'Structured data with set format and metadata conventions'), (b'Interoperable', b'Interoperable data with formats and metadata conventions for specific community tools'), (b'InProject', b'Data management within the project only. No archive involvement'), (b'OtherRepositories', b'Other Non-NERC repositories'), (b'BODC', b'British Oceanographic Data Centre'), (b'EIDC', b'Environmental Information Data Centre '), (b'PDC', b'Polar Data Centre'), (b'NGDC', b'National Geoscience Data Centre'), (b'OtherDMP', b'This data is planned within another project DMP'), (b'KeepIndefinitely', b'Keep Indefinitely'), (b'KeepAsIs', b'Keep as is - Even if obsolete'), (b'Dispose5years ', b'Review for disposal 5 years after project completes'), (b'ManageInProject', b"Don't Archive - manage the data within the project"), (b'Subset', b'Plan to keep a subset of the data indefinitely'), (b'TBD', b'TBD')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='helpscout_url',
            field=models.URLField(blank=True, null=True, verbose_name=b'OpMan URL'),
        ),
    ]
