# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('datavol', sizefield.models.FileSizeField(default=0)),
                ('contact1', models.CharField(blank=True, max_length=200, null=True)),
                ('contact2', models.CharField(blank=True, max_length=200, null=True)),
                ('deliverydate', models.DateField(blank=True, null=True)),
                ('preservation_plan', models.CharField(blank=True, choices=[(b'KeepIndefinitely', b'Keep Indefinitely'), (b'KeepAsIs', b'Keep as is - Even if obsolete'), (b'Dispose5years ', b'Review for disposal 5 years after project completes'), (b'ManageInProject', b"Don't Archive - manage the data within the project"), (b'Subset', b'Plan to keep a subset of the data indefinitely'), (b'TBD', b'TBD')], max_length=200, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[(b'WithProjectTeam', b'With Project Team'), (b'Ingesting', b'Ingesting'), (b'Archived', b'Archived and complete'), (b'Defaulted', b'Defaulted - not archived due to project not supplying data'), (b'NotArchived', b'Not going to archive - planned')], max_length=200, null=True)),
                ('data_URL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=800, null=True)),
                ('pi', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('data_activities', models.TextField(blank=True, help_text=b'Short description of data generation activities. eg Data will be collected by FAAM aircraft/ground instruments. Are there intensive measurement campaigns?', null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('dmp_agreed', models.DateField(blank=True, null=True)),
                ('initial_contact', models.DateField(blank=True, null=True)),
                ('PI', models.CharField(blank=True, max_length=200, null=True)),
                ('PIemail', models.EmailField(blank=True, max_length=200, null=True)),
                ('PIinst', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact1', models.CharField(blank=True, max_length=200, null=True)),
                ('Contact2', models.CharField(blank=True, max_length=200, null=True)),
                ('projectcost', models.IntegerField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(b'Proposal', b'Proposal'), (b'NotFunded', b'Not Funded'), (b'NotStarted', b'NotStarted'), (b'Active', b'Active'), (b'NoData', b'NoData'), (b'EndedWithDataToCome', b'Ended with data to come'), (b'Defaulted', b'Defaulted'), (b'Complete', b'Complete')], max_length=200, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_URL', models.URLField(blank=True, null=True)),
                ('project_usergroup', models.CharField(blank=True, help_text=b'Group name for registration for this group', max_length=200, null=True)),
                ('sciSupContact', models.ForeignKey(blank=True, help_text=b'CEDA person contact for this Project', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('third_party_data', models.ManyToManyField(blank=True, null=True, related_name='_project_third_party_data_+', to='dmp.DataProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('projects', models.ManyToManyField(blank=True, null=True, to='dmp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='grant',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dmp.Project'),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='project',
            field=models.ForeignKey(blank=True, help_text=b'Project producing this data', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmp.Project'),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='sciSupContact',
            field=models.ForeignKey(blank=True, help_text=b'CEDA person contact for this data', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
