# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataproduct',
            name='dmp_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
