# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from dmp.models import *
from datetime import datetime
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User



def migrate_project_notes(apps, schema_editor):
    Project = apps.get_model("dmp","Project")

    for project in Project.objects.all():
        if project.notes:

            instance = Note()

            instance.added = datetime.now()
            #instance.creator = User.objects.get(username='rsmith')
            instance.notes = "Notes migrated from previous version\n\n %s" % (project.notes)
            instance.content_type =  ContentType.objects.get(app_label="dmp", model="project")
            instance.object_id = project.pk
            instance.save()



def migrate_data_product_notes(apps,schema_editor):
    DataProduct = apps.get_model("dmp","DataProduct")

    for product in DataProduct.objects.all():
        if product.notes:

            instance = Note()

            instance.added = datetime.now()
            #instance.creator =  User.objects.get(username='rsmith')
            instance.notes = "Notes migrated from previous version\n\n %s" % (product.notes)
            instance.content_type = ContentType.objects.get(app_label="dmp", model="dataproduct")
            instance.object_id = product.pk
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmp', '0002_dataproduct_dmp_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),

        migrations.AlterField(
            model_name='note',
            name='creator',
            field=models.ForeignKey(null=True, blank=True, to=settings.AUTH_USER_MODEL)),

        # Migrate model data from notes textfield to new model.
        migrations.RunPython(migrate_project_notes),
        migrations.RunPython(migrate_data_product_notes),


        migrations.RemoveField(
            model_name='dataproduct',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='notes',
        ),
    ]
