# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 12:17
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('dmp', '0004_auto_20161124_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['added'], 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='project',
            name='sciSupContact',
            field=models.ForeignKey(blank=True, help_text=b'CEDA person contact for this Project', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmp.Person'),
        ),
    ]
