# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0005_auto_20161129_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('username',)},
        ),
    ]
