# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dmp', '0007_auto_20161129_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('form_type', models.CharField(blank=True, choices=[(b'projectForm', b'Project Form'), (b'instrumentForm', b'Instrument Form')], max_length=200, null=True)),
                ('form_link', models.URLField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='dmp_URL',
            field=models.URLField(blank=True, null=True, verbose_name=b'DMP URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dmp_agreed',
            field=models.DateField(blank=True, null=True, verbose_name=b'DMP Agreed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateField(blank=True, null=True, verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_contact',
            field=models.DateField(blank=True, null=True, verbose_name=b'Initial Contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name=b'Start Date'),
        ),
    ]
