# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0009_auto_20161209_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='template_ref',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
