# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0010_emailtemplates_template_ref'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emailtemplates',
            new_name='EmailTemplate',
        ),
    ]
