# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0014_auto_20161221_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_dataCentres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_dataCentre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
