# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0015_auto_20161223_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogstats',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
