# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0016_auto_20161223_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='draftDmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_dmp', models.TextField(blank=True)),
            ],
        ),
    ]
