# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmp', '0017_auto_20170131_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='draftDmp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_dmp_name', models.CharField(default=b'Draft DMP', max_length=200)),
                ('draft_dmp_content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Draft DMP',
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_expiry', models.DateTimeField()),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Token',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('reminder', models.CharField(choices=[(b'custom', b'Custom Date'), (b'1_week', b'1 Week'), (b'2_weeks', b'2 Weeks'), (b'1_month', b'1 Month'), (b'3_months', b'3 Months'), (b'-6_months', b'6 Months before end date'), (b'-3_months', b'3 Months before end date'), (b'-1_month', b'1 Month before end date')], max_length=200, verbose_name=b'Remind in')),
                ('due_date', models.DateField()),
                ('state', models.CharField(choices=[(b'Open', b'Open'), (b'Complete', b'Complete')], default=b'Open', max_length=200, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmp.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_ref',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Short Name'),
        ),
    ]
