# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0017_auto_20170112_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_contents', picklefield.fields.PickledObjectField(editable=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name=b'Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_dataCentres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Other Datacentres'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_dataCentre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Primary Datacentre'),
        ),
    ]
