# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0018_auto_20170301_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='lead_grant',
            field=models.BooleanField(default=False),
        ),
    ]
