# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0019_grant_lead_grant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[(b'Proposal', b'Proposal'), (b'NotFunded', b'Not Funded'), (b'NotStarted', b'Not Started'), (b'Active', b'Active'), (b'NoData', b'No Data'), (b'EndedWithDataToCome', b'Ended with data to come'), (b'Defaulted', b'Defaulted'), (b'NoDataForUs', b'No data for us'), (b'Complete', b'Complete'), (b'Unresponsive', b'Unresponsive')], max_length=200, null=True),
        ),
    ]
