# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0017_auto_20170112_1911'),
        ('dmp', '0019_auto_20170109_1539'),
    ]

    operations = [
    ]
