# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0020_auto_20170220_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder',
            field=models.CharField(choices=[(b'custom', b'Custom Date'), (b'1_week', b'1 Week'), (b'2_weeks', b'2 Weeks'), (b'1_month', b'1 Month'), (b'3_months', b'3 Months'), (b'-6_months', b'6 Months before end date'), (b'-3_months', b'3 Months before end date'), (b'-1_month', b'1 Month before end date')], max_length=200, verbose_name=b'Remind in'),
        ),
    ]
