# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0021_auto_20170224_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
