# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-09 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0022_auto_20180206_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='programme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
