# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0022_oauthtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthtoken',
            name='id_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='oauthtoken',
            name='invalid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
