# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0023_auto_20170113_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtoken',
            name='id_token',
        ),
        migrations.RemoveField(
            model_name='oauthtoken',
            name='invalid',
        ),
    ]
