# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0025_merge_20170315_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='lead_grant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='state',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Complete', b'Complete')], default=b'Open', max_length=200, null=True),
        ),
    ]
