# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0026_auto_20170315_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[(b'Proposal', b'Proposal'), (b'NotFunded', b'Not Funded'), (b'NotStarted', b'Not Started'), (b'Active', b'Active'), (b'NoData', b'No Data'), (b'EndedWithDataToCome', b'Ended with data to come'), (b'Defaulted', b'Defaulted'), (b'NoDataForUs', b'No data for us'), (b'Complete', b'Complete'), (b'Unresponsive', b'Unresponsive')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder',
            field=models.CharField(blank=True, choices=[(b'custom', b'Custom Date'), (b'1_week', b'1 Week'), (b'2_weeks', b'2 Weeks'), (b'1_month', b'1 Month'), (b'3_months', b'3 Months'), (b'-6_months', b'6 Months before end date'), (b'-3_months', b'3 Months before end date'), (b'-1_month', b'1 Month before end date')], max_length=200, verbose_name=b'Remind in'),
        ),
    ]
