# Generated by Django 2.2.17 on 2020-11-26 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0026_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataproduct',
            name='preservation_plan',
            field=models.CharField(blank=True, choices=[('Reference', 'Reference data with principal use to provide evidence for publication'), ('Structured', 'Structured data with set format and metadata conventions'), ('Interoperable', 'Interoperable data with formats and metadata conventions for specific community tools'), ('InProject', 'Data management within the project only. No archive involvement'), ('OtherRepositories', 'Other Non-NERC repositories'), ('BODC', 'British Oceanographic Data Centre'), ('EIDC', 'Environmental Information Data Centre '), ('PDC', 'Polar Data Centre'), ('NGDC', 'National Geoscience Data Centre'), ('OtherDMP', 'This data is planned within another project DMP'), ('KeepIndefinitely', 'Keep Indefinitely'), ('KeepAsIs', 'Keep as is - Even if obsolete'), ('Dispose5years ', 'Review for disposal 5 years after project completes'), ('ManageInProject', "Don't Archive - manage the data within the project"), ('Subset', 'Plan to keep a subset of the data indefinitely'), ('TBD', 'TBD')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project producing this data', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmp.Project'),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='sciSupContact',
            field=models.ForeignKey(blank=True, help_text='CEDA person contact for this data', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('WithProjectTeam', 'With Project Team'), ('Ingesting', 'Ingesting'), ('Archived', 'Archived and complete'), ('Defaulted', 'Defaulted - not archived due to project not supplying data'), ('NotArchived', 'Not going to archive - planned')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='draftdmp',
            name='draft_dmp_name',
            field=models.CharField(default='Draft DMP', max_length=200),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_ref',
            field=models.CharField(max_length=200, null=True, verbose_name='Short Name'),
        ),
        migrations.AlterField(
            model_name='metadataform',
            name='form_type',
            field=models.CharField(blank=True, choices=[('projectForm', 'Project Form'), ('instrumentForm', 'Instrument Form'), ('datasetForm', 'Dataset Form'), ('platformForm', 'Platform Form')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='metadataform',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ODMP_URL',
            field=models.URLField(blank=True, help_text='Outline DMP URL autogenerated when using grant uploader, essentially a best guess. Edit as necessary.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='data_activities',
            field=models.TextField(blank=True, help_text='Short description of data generation activities. eg Data will be collected by FAAM aircraft/ground instruments. Are there intensive measurement campaigns?', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dmp_URL',
            field=models.URLField(blank=True, null=True, verbose_name='DMP URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dmp_agreed',
            field=models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='DMP Agreed'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='helpscout_url',
            field=models.URLField(blank=True, null=True, verbose_name='OpMan URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='initial_contact',
            field=models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='Initial Contact'),
        ),
        migrations.AlterField(
            model_name='project',
            name='other_dataCentres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Datacentres'),
        ),
        migrations.AlterField(
            model_name='project',
            name='primary_dataCentre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Primary Datacentre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('InitialContact', 'Initial contact'), ('DMPComms', 'DMP comms'), ('Progress', 'Progress'), ('DataDelivery', 'Data delivery')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_usergroup',
            field=models.CharField(blank=True, help_text='Group name for registration for this group', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sciSupContact',
            field=models.ForeignKey(blank=True, help_text='CEDA person contact for this Project', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmp.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sciSupContact2',
            field=models.ForeignKey(blank=True, help_text='CEDA person contact for this Project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sciSupContact2s', to='dmp.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(blank=True, help_text='Date format dd/mm/yyyy', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Proposal', 'Proposal'), ('NotFunded', 'Not Funded'), ('NotStarted', 'Not Started'), ('Active', 'Active'), ('NoData', 'No Data'), ('EndedWithDataToCome', 'Ended with data to come'), ('Defaulted', 'Defaulted'), ('NoDataForUs', 'No data for us'), ('Complete', 'Complete'), ('Unresponsive', 'Unresponsive'), ('MergedProject/HandledElsewhere', 'Merged Project/Handled Elsewhere')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder',
            field=models.CharField(blank=True, choices=[('custom', 'Custom Date'), ('1_week', '1 Week'), ('2_weeks', '2 Weeks'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('-6_months', '6 Months before end date'), ('-3_months', '3 Months before end date'), ('-1_month', '1 Month before end date')], max_length=200, verbose_name='Remind in'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='state',
            field=models.CharField(choices=[('Open', 'Open'), ('Complete', 'Complete')], default='Open', max_length=200, null=True),
        ),
    ]
