# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0028_auto_20170803_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='helpscout_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
