# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0029_project_helpscout_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='grant_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='helpscout_url',
            field=models.URLField(blank=True, null=True, verbose_name=b'Helpscout URL'),
        ),
    ]
