# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-01 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmp', '0033_auto_20190822_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[(b'Initial contact', b'Initial contact'), (b'DMP comms', b'DMP comms'), (b'Progress', b'Progress'), (b'Data delivery', b'Data delivery')], max_length=200, null=True),
        ),
    ]
